#!/bin/bash
set -e

cd $HOME
mkdir -p files
git clone $2 code
wget -nv -O files/repl-install.txt $3
wget -nv -O files/repl-run.txt $4
mkdir -p code/.io.livecode.ch
cp files/repl-install.txt code/.io.livecode.ch/repl-install
cp files/repl-run.txt code/.io.livecode.ch/repl-run
cd code
dos2unix .io.livecode.ch/repl-install
dos2unix .io.livecode.ch/repl-run
chmod 755 .io.livecode.ch/repl-install
chmod 755 .io.livecode.ch/repl-run
timeout $1 .io.livecode.ch/repl-install
