#!/bin/bash                                                                                                                                                            
set -e
 
cd $HOME
mkdir -p files

wget -nv -O files/in.txt $3

cd code

timeout $1 $2 $HOME/files/in.txt
